services:
  email-audit-service:
    build:
      context: .
    command: >
      --email-threads data/employee_reply_email_with_image_attachment.eml
      --employee-domain @test.com
      --rules GREETING CLARITY GRAMMAR TONE
